language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - pip install coveralls
# command to run tests
script:
  - coverage run run_doctests.py
after_success:
  - coveralls
